# -*- coding: utf-8 -*-
"""week6 assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Octim_A_blBmJk9BxLPRxhw8uHmNVkh
"""

flowerlist = ["장미","백합","튤립","국화","수선화"]

flowerlist.append("해바라기")

newindex = sorted(flowerlist,key=len,reverse=True)

for name in range (len(newindex)):
  print (newindex[name],(len(newindex[name])))

movielist = [("오징어게임",50.45), ("이터널스",35.46),("그레비티",9.8), ("노타임투다이",52.5), ("스파이더맨",15.47)]
rank = 1
newindex = sorted(movielist, key = lambda x:x [1], reverse = True)

print ("영화제목           예매율            순위")
print ("=========        ======          ====")

for name,rate in newindex:
  print (name,"   \t",rate,"    \t",rank)
  rank += 1